"""tenant behavior profile

Revision ID: 0c2fd42a6785
Revises: 71472938e6eb
Create Date: 2026-02-18 19:03:36.940121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0c2fd42a6785'
down_revision: Union[str, Sequence[str], None] = '4b1c2d3e4f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DROP INDEX IF EXISTS ix_tenant_policy_tenant_id"))
    op.execute(sa.text("DROP TABLE IF EXISTS tenant_policy"))
    is_sqlite = op.get_bind().dialect.name == "sqlite"

    if is_sqlite:
        # SQLite needs table-rebuild semantics for column type/nullability changes.
        with op.batch_alter_table('request_audit_logs', recreate='always') as batch_op:
            batch_op.alter_column('tenant_id',
                                  existing_type=sa.INTEGER(),
                                  type_=sa.String(),
                                  existing_nullable=False)
            batch_op.alter_column('payload_hash',
                                  existing_type=sa.TEXT(),
                                  type_=sa.String(),
                                  existing_nullable=True)

        with op.batch_alter_table('system_events', recreate='always') as batch_op:
            batch_op.alter_column('tenant_id',
                                  existing_type=sa.INTEGER(),
                                  type_=sa.String(),
                                  existing_nullable=True)

        with op.batch_alter_table('tenant_risk_state', recreate='always') as batch_op:
            batch_op.alter_column('tenant_id',
                                  existing_type=sa.INTEGER(),
                                  type_=sa.String(),
                                  existing_nullable=True)
            batch_op.alter_column('quarantined',
                                  existing_type=sa.BOOLEAN(),
                                  nullable=True,
                                  existing_server_default=sa.text('0'))

        with op.batch_alter_table('usage_counters', recreate='always') as batch_op:
            batch_op.alter_column('tenant_id',
                                  existing_type=sa.INTEGER(),
                                  type_=sa.String(),
                                  existing_nullable=False)
    else:
        op.alter_column('mitigation_logs', 'id',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   autoincrement=True)
        op.alter_column('request_audit_logs', 'tenant_id',
                   existing_type=sa.INTEGER(),
                   type_=sa.String(),
                   existing_nullable=False)
        op.alter_column('request_audit_logs', 'payload_hash',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
        op.alter_column('system_events', 'tenant_id',
                   existing_type=sa.INTEGER(),
                   type_=sa.String(),
                   existing_nullable=True)
        op.alter_column('tenant_risk_state', 'tenant_id',
                   existing_type=sa.INTEGER(),
                   type_=sa.String(),
                   existing_nullable=True)
        op.alter_column('tenant_risk_state', 'quarantined',
                   existing_type=sa.BOOLEAN(),
                   nullable=True,
                   existing_server_default=sa.text('0'))
        op.alter_column('usage_counters', 'tenant_id',
                   existing_type=sa.INTEGER(),
                   type_=sa.String(),
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    is_sqlite = op.get_bind().dialect.name == "sqlite"

    if is_sqlite:
        with op.batch_alter_table('usage_counters', recreate='always') as batch_op:
            batch_op.alter_column('tenant_id',
                                  existing_type=sa.String(),
                                  type_=sa.INTEGER(),
                                  existing_nullable=False)

        with op.batch_alter_table('tenant_risk_state', recreate='always') as batch_op:
            batch_op.alter_column('quarantined',
                                  existing_type=sa.BOOLEAN(),
                                  nullable=False,
                                  existing_server_default=sa.text('0'))
            batch_op.alter_column('tenant_id',
                                  existing_type=sa.String(),
                                  type_=sa.INTEGER(),
                                  existing_nullable=True)

        with op.batch_alter_table('system_events', recreate='always') as batch_op:
            batch_op.alter_column('tenant_id',
                                  existing_type=sa.String(),
                                  type_=sa.INTEGER(),
                                  existing_nullable=True)

        with op.batch_alter_table('request_audit_logs', recreate='always') as batch_op:
            batch_op.alter_column('payload_hash',
                                  existing_type=sa.String(),
                                  type_=sa.TEXT(),
                                  existing_nullable=True)
            batch_op.alter_column('tenant_id',
                                  existing_type=sa.String(),
                                  type_=sa.INTEGER(),
                                  existing_nullable=False)
    else:
        op.alter_column('usage_counters', 'tenant_id',
                   existing_type=sa.String(),
                   type_=sa.INTEGER(),
                   existing_nullable=False)
        op.alter_column('tenant_risk_state', 'quarantined',
                   existing_type=sa.BOOLEAN(),
                   nullable=False,
                   existing_server_default=sa.text('0'))
        op.alter_column('tenant_risk_state', 'tenant_id',
                   existing_type=sa.String(),
                   type_=sa.INTEGER(),
                   existing_nullable=True)
        op.alter_column('system_events', 'tenant_id',
                   existing_type=sa.String(),
                   type_=sa.INTEGER(),
                   existing_nullable=True)
        op.alter_column('request_audit_logs', 'payload_hash',
                   existing_type=sa.String(),
                   type_=sa.TEXT(),
                   existing_nullable=True)
        op.alter_column('request_audit_logs', 'tenant_id',
                   existing_type=sa.String(),
                   type_=sa.INTEGER(),
                   existing_nullable=False)
        op.alter_column('mitigation_logs', 'id',
                   existing_type=sa.INTEGER(),
                   nullable=True,
                   autoincrement=True)
    op.create_table('tenant_policy',
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('policy_name', sa.VARCHAR(), nullable=False),
    sa.Column('rerason_snapshot', sqlite.JSON(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_index(op.f('ix_tenant_policy_tenant_id'), 'tenant_policy', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
