"""update tenant api key hash

Revision ID: 0e91cab4cc37
Revises: ff47515596a1
Create Date: 2026-03-23 11:19:15.116079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0e91cab4cc37'
down_revision: Union[str, Sequence[str], None] = 'ff47515596a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('api_key_hash', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE tenants SET api_key_hash = api_key WHERE api_key_hash IS NULL")
    op.alter_column('tenants', 'api_key_hash', nullable=False)
    op.drop_index(op.f('ix_tenants_api_key'), table_name='tenants')
    op.create_unique_constraint(None, 'tenants', ['api_key_hash'])
    op.drop_column('tenants', 'api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('api_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tenants', type_='unique')
    op.create_index(op.f('ix_tenants_api_key'), 'tenants', ['api_key'], unique=True)
    op.drop_column('tenants', 'expires_at')
    op.drop_column('tenants', 'api_key_hash')
    # ### end Alembic commands ###
