"""add global system state

Revision ID: 1abab5650e71
Revises: f4b7a2d1c9e0
Create Date: 2026-03-12 18:45:00.903384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1abab5650e71'
down_revision: Union[str, Sequence[str], None] = 'f4b7a2d1c9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'global_system_state',
        sa.Column('id', sa.String(), primary_key=True, server_default=sa.text("'GLOBAL'")),
        sa.Column('adaptive_engine_frozen', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('freeze_reason', sa.String(), nullable=True),
        sa.Column('frozen_at', sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_system_state')
    # ### end Alembic commands ###
