"""mitigation strategy performance

Revision ID: 3533043a76e2
Revises: 0c2fd42a6785
Create Date: 2026-02-19 12:09:40.428357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '3533043a76e2'
down_revision: Union[str, Sequence[str], None] = '0c2fd42a6785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if 'tenant_policy' in inspector.get_table_names():
        index_names = {idx['name'] for idx in inspector.get_indexes('tenant_policy')}
        index_name = op.f('ix_tenant_policy_tenant_id')
        if index_name in index_names:
            op.drop_index(index_name, table_name='tenant_policy')
        op.drop_table('tenant_policy')

    if bind.dialect.name != "sqlite":
        op.alter_column('mitigation_logs', 'id',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if bind.dialect.name != "sqlite":
        op.alter_column('mitigation_logs', 'id',
                   existing_type=sa.INTEGER(),
                   nullable=True,
                   autoincrement=True)
    if 'tenant_policy' not in inspector.get_table_names():
        op.create_table('tenant_policy',
        sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
        sa.Column('policy_name', sa.VARCHAR(), nullable=False),
        sa.Column('rerason_snapshot', sqlite.JSON(), nullable=True),
        sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('tenant_id')
        )
    index_names = {idx['name'] for idx in sa.inspect(bind).get_indexes('tenant_policy')}
    index_name = op.f('ix_tenant_policy_tenant_id')
    if index_name not in index_names:
        op.create_index(index_name, 'tenant_policy', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
