"""add alert lifecycle fields

Revision ID: ff47515596a1
Revises: 7f8a1c2d3e4b
Create Date: 2026-03-20 17:59:29.924644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff47515596a1'
down_revision: Union[str, Sequence[str], None] = '7f8a1c2d3e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_governance_alerts_tenant_id'), table_name='governance_alerts')
    op.drop_table('governance_alerts')
    op.drop_table('global_system_state')
    op.drop_index(op.f('ix_mitigation_strategy_performance_strategy'), table_name='mitigation_strategy_performance')
    op.drop_index(op.f('ix_mitigation_strategy_performance_tenant_id'), table_name='mitigation_strategy_performance')
    op.drop_table('mitigation_strategy_performance')
    op.drop_index(op.f('ix_governance_anchors_id'), table_name='governance_anchors')
    op.drop_table('governance_anchors')
    op.drop_index(op.f('ix_governance_keys_key_id'), table_name='governance_keys')
    op.drop_table('governance_keys')
    op.drop_index(op.f('ix_decision_snapshots_tenant_id'), table_name='decision_snapshots')
    op.drop_table('decision_snapshots')
    op.drop_index(op.f('ix_training_snapshots_tenant_id'), table_name='training_snapshots')
    op.drop_table('training_snapshots')
    op.drop_index(op.f('ix_tenant_policy_tenant_id'), table_name='tenant_policy')
    op.drop_table('tenant_policy')
    op.drop_index(op.f('ix_tenant_system_state_tenant_id'), table_name='tenant_system_state')
    op.drop_table('tenant_system_state')
    op.alter_column('behavior_memory', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_mitigation_logs_id'), 'mitigation_logs', ['id'], unique=False)
    op.create_index(op.f('ix_system_events_id'), 'system_events', ['id'], unique=False)
    op.alter_column('tenant_usage', 'request_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('tenant_usage', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenant_usage', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_tenant_usage_day'), 'tenant_usage', type_='unique')
    op.create_index(op.f('ix_tenant_usage_tenant_id'), 'tenant_usage', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_usage_daily_tenant_id'), 'tenant_usage_daily', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_usage_monthly_tenant_id'), 'tenant_usage_monthly', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_usage_monthly_tenant_id'), table_name='tenant_usage_monthly')
    op.drop_index(op.f('ix_tenant_usage_daily_tenant_id'), table_name='tenant_usage_daily')
    op.drop_index(op.f('ix_tenant_usage_tenant_id'), table_name='tenant_usage')
    op.create_unique_constraint(op.f('uq_tenant_usage_day'), 'tenant_usage', ['tenant_id', 'path', 'method', 'usage_date'], postgresql_nulls_not_distinct=False)
    op.alter_column('tenant_usage', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenant_usage', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenant_usage', 'request_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_system_events_id'), table_name='system_events')
    op.drop_index(op.f('ix_mitigation_logs_id'), table_name='mitigation_logs')
    op.alter_column('behavior_memory', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table('tenant_system_state',
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('adaptive_engine_frozen', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('freeze_reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('freeze_locked_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('frozen_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('tenant_id', name=op.f('tenant_system_state_pkey'))
    )
    op.create_index(op.f('ix_tenant_system_state_tenant_id'), 'tenant_system_state', ['tenant_id'], unique=False)
    op.create_table('tenant_policy',
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('policy_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rerason_snapshot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', name=op.f('tenant_policy_pkey'))
    )
    op.create_index(op.f('ix_tenant_policy_tenant_id'), 'tenant_policy', ['tenant_id'], unique=False)
    op.create_table('training_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('velocity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('stability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bias', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('forecast_peak', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('forecast_accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('adaptive_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volatility', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_strategy_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('long_term_success_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('short_term_success_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('escalated', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('training_snapshots_pkey'))
    )
    op.create_index(op.f('ix_training_snapshots_tenant_id'), 'training_snapshots', ['tenant_id'], unique=False)
    op.create_table('decision_snapshots',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('context', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('strategy_stats_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('selected_strategy', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('regret', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('random_seed', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('engine_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('previous_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('decision_snapshots_pkey'))
    )
    op.create_index(op.f('ix_decision_snapshots_tenant_id'), 'decision_snapshots', ['tenant_id'], unique=False)
    op.create_table('governance_keys',
    sa.Column('key_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('encrypted_secret', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key_id', name=op.f('governance_keys_pkey'))
    )
    op.create_index(op.f('ix_governance_keys_key_id'), 'governance_keys', ['key_id'], unique=False)
    op.create_table('governance_anchors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('anchored_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('anchor_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('anchored_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('governance_anchors_pkey'))
    )
    op.create_index(op.f('ix_governance_anchors_id'), 'governance_anchors', ['id'], unique=False)
    op.create_table('mitigation_strategy_performance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('strategy', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('success_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('failure_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('short_term_success', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('short_term_failure', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('mitigation_strategy_performance_pkey'))
    )
    op.create_index(op.f('ix_mitigation_strategy_performance_tenant_id'), 'mitigation_strategy_performance', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_mitigation_strategy_performance_strategy'), 'mitigation_strategy_performance', ['strategy'], unique=False)
    op.create_table('global_system_state',
    sa.Column('id', sa.VARCHAR(), server_default=sa.text("'GLOBAL'::character varying"), autoincrement=False, nullable=False),
    sa.Column('adaptive_engine_frozen', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('freeze_reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('frozen_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('freeze_locked_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('platform_override_active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('platform_override_reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('platform_override_locked_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('platform_override_activated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('global_system_state_pkey'))
    )
    op.create_table('governance_alerts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('alert_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('governance_alerts_pkey'))
    )
    op.create_index(op.f('ix_governance_alerts_tenant_id'), 'governance_alerts', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
